"use strict";

document.addEventListener("DOMContentLoaded", async () => {
  const folderHost = document.getElementById("favorites-folders");
  const grid = document.getElementById("favorites-grid");
  const empty = document.getElementById("favorites-empty");
  const search = document.getElementById("favorites-search");
  const currentTitle = document.getElementById("favorites-current-title");
  const currentCount = document.getElementById("favorites-current-count");
  const status = document.getElementById("favorites-status");
  const fileInput = document.getElementById("favorites-import-file");
  const coverSources = new WeakMap();
  const starPath = "M12 2.8l2.8 5.7 6.3.9-4.55 4.43 1.08 6.25L12 17.1l-5.63 2.98 1.08-6.25L1.82 9.4l6.3-.9Z";
  let activeFolder = "all";
  let query = "";
  let items = [];

  const node = (tag, className, value) => { const element = document.createElement(tag); if (className) element.className = className; if (value !== undefined) element.textContent = String(value); return element; };
  const starIcon = (favorite) => { const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg"); svg.setAttribute("viewBox", "0 0 24 24"); svg.setAttribute("aria-hidden", "true"); const path = document.createElementNS("http://www.w3.org/2000/svg", "path"); path.setAttribute("d", starPath); path.setAttribute("fill", favorite ? "currentColor" : "none"); path.setAttribute("stroke", "currentColor"); path.setAttribute("stroke-width", "1.8"); path.setAttribute("stroke-linejoin", "round"); svg.append(path); return svg; };
  const setStatus = (message) => { status.textContent = message; };
  function setStar(button, item) { const favorite = Favorites.isFavorite(item.id); button.replaceChildren(starIcon(favorite)); button.setAttribute("aria-pressed", String(favorite)); button.setAttribute("aria-label", `${favorite ? "取消收藏" : "收藏"}：《${item.title}》`); }
  function sourceImage(image, item) { const hasCover = typeof item.cover === "string" && item.cover.trim(); image.src = hasCover ? item.cover : getCoverPlaceholder(item); image.dataset.coverFallback = String(!hasCover); image.alt = `${item.title}的封面`; image.loading = "lazy"; image.width = 640; image.height = 480; coverSources.set(image, item); }
  function folderCount(folderId) { return Favorites.getEntries().filter((entry) => entry.folderIds.includes(folderId)).length; }
  function renderFolders() {
    const allButton = document.createElement("button"); allButton.type = "button"; allButton.className = "favorites-folder-button"; allButton.dataset.folder = "all"; allButton.setAttribute("aria-pressed", String(activeFolder === "all")); allButton.append(node("span", "favorites-folder-name", "全部收藏"), node("span", "favorites-folder-count", Favorites.getAll().length)); folderHost.replaceChildren(allButton);
    Favorites.getFolders().forEach((folder) => { const row = node("div", "favorites-folder-row"); const button = document.createElement("button"); button.type = "button"; button.className = "favorites-folder-button"; button.dataset.folder = folder.id; button.setAttribute("aria-pressed", String(activeFolder === folder.id)); button.append(node("span", "favorites-folder-name", folder.name), node("span", "favorites-folder-count", folderCount(folder.id))); const actions = node("span", "favorites-folder-actions"); const rename = document.createElement("button"); rename.type = "button"; rename.className = "folder-action"; rename.dataset.renameFolder = folder.id; rename.setAttribute("aria-label", `重命名${folder.name}`); rename.textContent = "改名"; const remove = document.createElement("button"); remove.type = "button"; remove.className = "folder-action danger"; remove.dataset.deleteFolder = folder.id; remove.setAttribute("aria-label", `删除${folder.name}`); remove.textContent = "删除"; actions.append(rename, remove); row.append(button, actions); folderHost.append(row); });
  }
  function beginRename(folderId, row) { const folder = Favorites.getFolders().find((item) => item.id === folderId); if (!folder) return; const input = document.createElement("input"); input.className = "folder-rename-input"; input.value = folder.name; input.setAttribute("aria-label", "收藏夹名称"); const name = row.querySelector(".favorites-folder-name"); name.replaceChildren(input); input.focus(); input.select(); let done = false; const finish = (save) => { if (done) return; done = true; if (save && input.value.trim()) Favorites.renameFolder(folderId, input.value); render(); }; input.addEventListener("blur", () => finish(true)); input.addEventListener("keydown", (event) => { if (event.key === "Enter") finish(true); if (event.key === "Escape") finish(false); }); }
  function visibleItems() { const entries = new Map(Favorites.getEntries().map((entry) => [entry.id, entry])); return items.filter((item) => { const entry = entries.get(item.id); if (!entry || !Favorites.isFavorite(item.id)) return false; if (activeFolder !== "all" && !entry.folderIds.includes(activeFolder)) return false; if (!query) return true; const haystack = [item.title, item.prompt, item.promptZh, entry.note, ...Store.normalizeTags(item.tags)].join(" ").toLocaleLowerCase(); return haystack.includes(query); }); }
  function createFolderPicker(item) { const panel = node("div", "favorites-folder-picker"); panel.hidden = true; Favorites.getFolders().forEach((folder) => { const label = node("label", "folder-picker-option"); const checkbox = document.createElement("input"); checkbox.type = "checkbox"; checkbox.checked = Favorites.isInFolder(item.id, folder.id); checkbox.dataset.folderId = folder.id; label.append(checkbox, node("span", "", folder.name)); panel.append(label); }); panel.addEventListener("change", (event) => { const checkbox = event.target.closest("input[data-folder-id]"); if (checkbox) Favorites.toggleInFolder(item.id, checkbox.dataset.folderId); }); return panel; }
  function createCard(item) { const entry = Favorites.getEntry(item.id); const article = node("article", "card favorites-card"); article.dataset.id = item.id; article.tabIndex = 0; article.setAttribute("role", "button"); const link = document.createElement("a"); link.className = "favorites-card-link"; link.href = `library.html?id=${encodeURIComponent(item.id)}`; const cover = node("div", "card-cover"); const image = document.createElement("img"); sourceImage(image, item); const label = node("span", "cover-label", "封面待添加"); label.hidden = image.dataset.coverFallback !== "true"; cover.append(image, label); const body = node("div", "card-body"); body.append(node("div", "card-meta", CONFIG.typeLabels[item.type] || item.type), node("h3", "", item.title), node("p", "card-description", item.promptZh || "")); const meta = body.querySelector(".card-meta"); if (item.featured === true) meta.append(node("span", "featured-badge", "精选")); if (typeof Stats !== "undefined" && Stats.getCopyCount(item.id) > 0) { const badge = node("span", "copy-count", `你复制过 ${Stats.getCopyCount(item.id)} 次`); badge.title = "统计仅保存在你自己的浏览器中"; meta.append(badge); } const tags = node("div", "tags"); Store.normalizeTags(item.tags).forEach((tag) => tags.append(node("span", "tag", tag))); body.append(tags); link.append(cover, body); article.append(link); const star = document.createElement("button"); star.type = "button"; star.className = "favorite-button"; star.dataset.favorite = item.id; setStar(star, item); article.append(star); const actions = node("div", "favorites-card-actions"); const foldersButton = document.createElement("button"); foldersButton.type = "button"; foldersButton.className = "button button-small"; foldersButton.dataset.folderPicker = item.id; foldersButton.textContent = "加入收藏夹"; const noteButton = document.createElement("button"); noteButton.type = "button"; noteButton.className = "button button-small"; noteButton.dataset.noteEditor = item.id; noteButton.textContent = entry && entry.note ? "编辑备注" : "写备注"; actions.append(foldersButton, noteButton, createFolderPicker(item)); article.append(actions); if (entry && entry.note) article.append(node("p", "favorites-note", entry.note)); return article; }
  function renderCards() { const allCount = Favorites.getAll().length; const visible = visibleItems(); const folder = Favorites.getFolders().find((item) => item.id === activeFolder); currentTitle.textContent = activeFolder === "all" ? "全部收藏" : (folder ? folder.name : "收藏夹"); currentCount.textContent = `${visible.length} 条`; grid.replaceChildren(...visible.map(createCard)); grid.setAttribute("aria-busy", "false"); if (!allCount) empty.textContent = "还没有收藏任何提示词，请先去提示词库收藏。"; else if (!visible.length && query) empty.textContent = "没有找到匹配的收藏。"; else if (!visible.length) empty.textContent = "当前收藏夹还是空的，可以从卡片的“加入收藏夹”面板添加提示词。"; empty.hidden = Boolean(visible.length); }
  function render() { renderFolders(); renderCards(); }
  function editNote(card, item) { const entry = Favorites.getEntry(item.id); const input = document.createElement("textarea"); input.className = "favorites-note-input"; input.value = entry ? entry.note : ""; input.rows = 2; input.setAttribute("aria-label", `编辑${item.title}备注`); const current = card.querySelector(".favorites-note"); if (current) current.replaceWith(input); else card.append(input); input.focus(); let done = false; const finish = (save) => { if (done) return; done = true; if (save) Favorites.setNote(item.id, input.value.trim()); else render(); }; input.addEventListener("blur", () => finish(true)); input.addEventListener("keydown", (event) => { if (event.key === "Escape") { event.preventDefault(); finish(false); } if (event.key === "Enter" && !event.shiftKey) { event.preventDefault(); finish(true); } }); }
  folderHost.addEventListener("click", (event) => { const rename = event.target.closest("[data-rename-folder]"); if (rename) { event.stopPropagation(); beginRename(rename.dataset.renameFolder, rename.closest(".favorites-folder-row")); return; } const remove = event.target.closest("[data-delete-folder]"); if (remove) { event.stopPropagation(); const folder = Favorites.getFolders().find((item) => item.id === remove.dataset.deleteFolder); if (folder && confirm(`确定删除“${folder.name}”吗？`)) { Favorites.deleteFolder(folder.id); if (activeFolder === folder.id) activeFolder = "all"; render(); } return; } const button = event.target.closest("[data-folder]"); if (button) { activeFolder = button.dataset.folder; render(); } });
  document.getElementById("create-folder").addEventListener("click", () => { const folder = Favorites.createFolder("我的收藏"); activeFolder = folder.id; render(); setStatus(`已创建收藏夹${folder.name}`); });
  grid.addEventListener("click", (event) => { const star = event.target.closest("button[data-favorite]"); if (star) { event.preventDefault(); event.stopPropagation(); Favorites.toggle(star.dataset.favorite); return; } const pickerButton = event.target.closest("button[data-folder-picker]"); if (pickerButton) { event.preventDefault(); event.stopPropagation(); const picker = pickerButton.parentElement.querySelector(".favorites-folder-picker"); picker.hidden = !picker.hidden; return; } const noteButton = event.target.closest("button[data-note-editor]"); if (noteButton) { event.preventDefault(); event.stopPropagation(); const item = items.find((record) => record.id === noteButton.dataset.noteEditor); if (item) editNote(noteButton.closest(".favorites-card"), item); } });
  grid.addEventListener("keydown", (event) => { if ((event.key === "Enter" || event.key === " ") && event.target.matches(".favorites-card")) { event.preventDefault(); const link = event.target.querySelector(".favorites-card-link"); if (link) location.href = link.href; } });
  grid.addEventListener("error", (event) => { const image = event.target; if (image.tagName !== "IMG" || image.dataset.coverFallback === "true") return; const item = coverSources.get(image); if (!item) return; image.dataset.coverFallback = "true"; image.src = getCoverPlaceholder(item); image.closest(".card-cover").querySelector(".cover-label").hidden = false; }, true);
  search.addEventListener("input", () => { query = search.value.trim().toLocaleLowerCase(); renderCards(); });
  document.getElementById("favorites-export").addEventListener("click", () => { const blob = new Blob([Favorites.exportJSON()], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `prompt-gallery-favorites-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 0); setStatus("收藏数据已导出"); });
  document.getElementById("favorites-import").addEventListener("click", () => fileInput.click());
  fileInput.addEventListener("change", () => { const file = fileInput.files && fileInput.files[0]; fileInput.value = ""; if (!file) return; if (file.size > 2 * 1024 * 1024) { setStatus("导入失败：文件不能超过 2MB。"); return; } const reader = new FileReader(); reader.onload = () => { const result = Favorites.importJSON(String(reader.result || "")); if (!result) { setStatus("导入失败：JSON 格式不正确。"); return; } setStatus(`已导入收藏夹 ${result.addedFolders} 个、收藏 ${result.addedEntries} 条。`); render(); }; reader.onerror = () => setStatus("导入失败：文件读取失败。"); reader.readAsText(file); });
  document.addEventListener("favorites:changed", render);
  document.addEventListener("stats:changed", () => {
    if (typeof Stats === "undefined") return;
    grid.querySelectorAll(".favorites-card[data-id]").forEach((card) => {
      const meta = card.querySelector(".card-meta");
      if (!meta) return;
      const count = Stats.getCopyCount(card.dataset.id);
      let badge = meta.querySelector(".copy-count");
      if (count > 0) {
        if (!badge) { badge = node("span", "copy-count"); meta.append(badge); }
        badge.textContent = `你复制过 ${count} 次`;
        badge.title = "统计仅保存在你自己的浏览器中";
      } else if (badge) badge.remove();
    });
  });
  try { items = await getPrompts(); Store.setData(items); render(); } catch (error) { Store.setData([]); grid.setAttribute("aria-busy", "false"); empty.textContent = "提示词暂时无法加载，请稍后刷新页面。"; empty.hidden = false; setStatus("提示词暂时无法加载"); console.warn("收藏页提示词加载失败。", error); }
});
